// TODO: REMOVE THIS FILE AFTER INTEGRATION TO API

const EVM_CHAINS = {
    1: {
        net: 'eth',
        name: 'Ethereum',
        native_token: {
            logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.svg',
            decimals: 18,
            name: 'Ether',
            symbol: 'ETH',
            coingecko_id: 'ethereum',
        },
        chain_id: 1,
        main_standards: ['erc20'],
        address_validating: '^0x([a-zA-Z0-9]{40})$',
        logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.svg',
        coingecko_id: 'ethereum',
        explorers: ['https://etherscan.io'],
        nodes: [
            'https://cloudflare-eth.com',
            'https://ethereum.publicnode.com',
            'https://mainnet.gateway.tenderly.co',
            'https://api.mycryptoapi.com/eth',
        ],
        derivation_path: {
            default: "m/44'/60'/0'/0",
            additional: "m/44'/137'/0'/0",
        },
    },
    56: {
        net: 'bsc',
        name: 'Binance Smart Chain',
        native_token: {
            logo: 'https://cryptologos.cc/logos/bnb-bnb-logo.svg',
            decimals: 18,
            name: 'BNB Chain Native Token',
            symbol: 'BNB',
            coingecko_id: 'binancecoin',
        },
        chain_id: 56,
        main_standards: ['bep20'],
        address_validating: '^0x([a-zA-Z0-9]{40})$',
        logo: 'https://cryptologos.cc/logos/bnb-bnb-logo.svg',
        coingecko_id: 'binancecoin',
        explorers: ['https://bscscan.com'],
        nodes: [
            'https://bsc.publicnode.com',
            'https://bsc-dataseed1.bnbchain.org',
            'https://bsc-dataseed2.bnbchain.org',
            'https://bsc-dataseed3.bnbchain.org',
            'https://bsc-dataseed4.bnbchain.org',
            'https://bsc-dataseed1.defibit.io',
            'https://bsc-dataseed2.defibit.io',
            'https://bsc-dataseed3.defibit.io',
            'https://bsc-dataseed4.defibit.io',
            'https://bsc-dataseed1.ninicoin.io',
            'https://bsc-dataseed2.ninicoin.io',
            'https://bsc-dataseed3.ninicoin.io',
            'https://bsc-dataseed4.ninicoin.io',
        ],
        derivation_path: {
            default: "m/44'/60'/0'/0",
            additional: "m/44'/137'/0'/0",
        },
    },
    42161: {
        net: 'arbitrum',
        name: 'Arbitrum',
        native_token: {
            logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.svg',
            coingecko_id: 'ethereum',
            decimals: 18,
            name: 'Ether',
            symbol: 'ETH',
        },
        chain_id: 42161,
        main_standards: ['erc20'],
        address_validating: '^0x([a-zA-Z0-9]{40})$',
        logo: 'https://cryptologos.cc/logos/arbitrum-arb-logo.png',
        coingecko_id: 'arbitrum',
        explorers: ['https://arbiscan.io', 'https://explorer.arbitrum.io'],
        nodes: ['https://arbitrum-one.publicnode.com', 'https://arb1.arbitrum.io/rpc'],
        derivation_path: {
            default: "m/44'/60'/0'/0",
            additional: "m/44'/137'/0'/0",
        },
    },
    137: {
        net: 'polygon',
        name: 'Polygon',
        native_token: {
            logo: 'https://cryptologos.cc/logos/polygon-matic-logo.png',
            decimals: 18,
            name: 'MATIC',
            symbol: 'MATIC',
            coingecko_id: 'matic-network',
        },
        chain_id: 137,
        main_standards: ['erc20'],
        address_validating: '^0x([a-zA-Z0-9]{40})$',
        logo: 'https://cryptologos.cc/logos/polygon-matic-logo.png',
        coingecko_id: 'matic-network',
        explorers: ['https://polygonscan.com'],
        nodes: [
            'https://polygon-rpc.com/',
            'https://rpc-mainnet.maticvigil.com',
            'https://polygon-bor.publicnode.com',
            'https://polygon.gateway.tenderly.co',
            'https://rpc-mainnet.matic.network',
            'https://matic-mainnet.chainstacklabs.com',
            'https://rpc-mainnet.matic.quiknode.pro',
            'https://matic-mainnet-full-rpc.bwarelabs.com',
        ],
        derivation_path: {
            default: "m/44'/60'/0'/0",
            additional: "m/44'/137'/0'/0",
        },
    },
    43114: {
        net: 'avalanche',
        name: 'Avalanche',
        native_token: {
            logo: 'https://cryptologos.cc/logos/avalanche-avax-logo.png',
            decimals: 18,
            name: 'Avalanche',
            symbol: 'AVAX',
            coingecko_id: 'avalanche-2',
        },
        chain_id: 43114,
        main_standards: ['erc20'],
        address_validating: '^0x([a-zA-Z0-9]{40})$',
        logo: 'https://cryptologos.cc/logos/avalanche-avax-logo.png',
        coingecko_id: 'avalanche-2',
        explorers: ['https://snowtrace.io'],
        nodes: ['https://avalanche-c-chain.publicnode.com', 'https://api.avax.network/ext/bc/C/rpc'],
        derivation_path: {
            default: "m/44'/60'/0'/0",
            additional: "m/44'/137'/0'/0",
        },
    },
    10: {
        net: 'optimism',
        name: 'Optimism',
        native_token: {
            logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.svg',
            coingecko_id: 'ethereum',
            decimals: 18,
            name: 'Ether',
            symbol: 'ETH',
        },
        chain_id: 10,
        main_standards: ['erc20'],
        address_validating: '^0x([a-zA-Z0-9]{40})$',
        logo: 'https://cryptologos.cc/logos/optimism-ethereum-op-logo.png',
        coingecko_id: 'optimism',
        explorers: ['https://optimistic.etherscan.io'],
        nodes: ['https://optimism.publicnode.com', 'https://optimism.gateway.tenderly.co', 'https://mainnet.optimism.io'],
        derivation_path: {
            default: "m/44'/60'/0'/0",
            additional: "m/44'/137'/0'/0",
        },
    },
    250: {
        net: 'fantom',
        name: 'Fantom',
        native_token: {
            logo: 'https://cryptologos.cc/logos/fantom-ftm-logo.png',
            decimals: 18,
            name: 'Fantom',
            symbol: 'FTM',
            coingecko_id: 'fantom',
        },
        chain_id: 250,
        main_standards: ['erc20'],
        address_validating: '^0x([a-zA-Z0-9]{40})$',
        logo: 'https://cryptologos.cc/logos/fantom-ftm-logo.png',
        coingecko_id: 'fantom',
        explorers: ['https://ftmscan.com'],
        nodes: ['https://rpc.ftm.tools', 'https://fantom.publicnode.com'],
        derivation_path: {
            default: "m/44'/60'/0'/0",
            additional: "m/44'/137'/0'/0",
        },
    },
    324: {
        net: 'zksync',
        name: 'zkSync',
        native_token: {
            logo: 'https://pulsar-images.s3.eu-west-1.amazonaws.com/tokens/Ethereum.png',
            coingecko_id: 'ethereum',
            verified: true,
            decimals: 18,
            name: 'Ether',
            symbol: 'ETH',
        },
        chain_id: 324,
        main_standards: ['erc20'],
        address_validating: '^0x([a-fA-F0-9]{40})$',
        logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/24091.png',
        coingecko_id: 'zksync',
        ecosystem: 'evm',
        explorers: ['https://explorer.zksync.io'],
        nodes: ['https://zksync.drpc.org', 'https://mainnet.era.zksync.io'],
        derivation_path: {
            default: "m/44'/60'/0'/0",
            additional: "m/44'/137'/0'/0",
        },
    },
};

const chainConfig = Object.keys(EVM_CHAINS).map((key) => {
    const chain = EVM_CHAINS[key];
    const hexString = chain.chain_id.toString(16);

    return {
        id: '0x' + hexString,
        label: chain.name,
        token: chain.native_token.symbol,
        rpcUrl: chain.nodes[0],
    };
});

export { chainConfig, EVM_CHAINS };
