export const PLATFORMS = {
    arbitrum: 'arbitrum-one',
    avalanche: 'avalanche-network',
    base: 'base',
    blast: 'blast',
    bsc: 'binance-smart-chain',
    celo: 'celo',
    cronos: 'cronos',
    eth: 'ethereum',
    fantom: 'fantom',
    gnosis: 'xdai',
    manta: 'manta',
    polygon: 'polygon-pos',
    optimism: 'optimistic-ethereum',
    linea: 'linea',
    scroll: 'scroll',
    mantle: 'mantle',
    zksync: 'zksync',
    zora: 'zora-network',
};
