import CitadelOneStake from '@/modules/shortcuts/data/citadel-stake.json';

export const SHORTCUTS = [
    CitadelOneStake,
    // {
    //     id: 'airdrop-farming-portfolio',
    //     name: 'Airdrop-farming portfolio Airdrop-farming portfolio',
    //     description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    //     logoURI: 'https://',
    //     wallpaper: '',
    //     type: 'stake',
    //     ecosystems: ['EVM'],
    //     minAmount: {
    //         value: 1,
    //         currency: 'ETH',
    //     },
    //     tags: ['best', 'staking'],
    //     author: {
    //         name: 'Zomet',
    //         avatar: 'https://zomet-logo.png',
    //     },
    //     recipe: {
    //         id: 'evm-osmosis-citadel-one-stake',
    //         operations: [
    //             {
    //                 id: 'bridge-eth-to-osmo',
    //                 name: 'Bridge Tokens to COSMOS (Osmosis)',
    //                 type: 'operation',
    //                 moduleType: 'superSwap',
    //                 operationType: 'bridge',
    //                 paramsInterface: 'IBridgeParams',
    //                 layoutComponent: 'SuperSwap',
    //                 skipConditions: [
    //                     {
    //                         name: 'srcNetwork',
    //                         value: 'osmosis',
    //                     },
    //                     {
    //                         name: 'srcToken',
    //                         value: 'osmosis:tokens__native:OSMO',
    //                     },
    //                 ],
    //                 params: [
    //                     {
    //                         name: 'srcNetwork',
    //                         disabled: false,
    //                         ecosystem: 'EVM',
    //                         chainId: 1,
    //                     },
    //                     {
    //                         name: 'srcToken',
    //                         disabled: false,
    //                         chain: 'eth',
    //                         id: 'eth:tokens__native:ETH',
    //                     },
    //                     {
    //                         name: 'dstNetwork',
    //                         disabled: true,
    //                         ecosystem: 'COSMOS',
    //                         chainId: 'osmosis',
    //                     },
    //                     {
    //                         name: 'dstToken',
    //                         disabled: true,
    //                         id: 'osmosis:tokens__native:OSMO',
    //                         chain: 'osmosis',
    //                     },
    //                     {
    //                         name: 'swapDirection',
    //                         disabled: true,
    //                     },
    //                 ],
    //             },
    //             {
    //                 id: 'swap-osmo-to-tokens',
    //                 name: 'Swap OSMO, ATOM, STARS',
    //                 type: 'recipe',
    //                 operationType: 'swap',
    //                 moduleType: 'superSwap',
    //                 paramsInterface: 'ISwapParams',
    //                 layoutComponent: 'SuperSwap',
    //                 operations: [
    //                     {
    //                         id: 'osmo-to-atom',
    //                         name: 'OSMO to ATOM',
    //                         type: 'operation',
    //                         operationType: 'swap',
    //                         moduleType: 'superSwap',
    //                         paramsInterface: 'ISwapParams',
    //                         layoutComponent: 'SuperSwap',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'osmosis',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'osmosis:tokens__native:OSMO',
    //                                 chain: 'osmosis',
    //                                 address: 'uosmo',
    //                             },
    //                             {
    //                                 name: 'dstNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'cosmoshub',
    //                             },
    //                             {
    //                                 name: 'dstToken',
    //                                 disabled: true,
    //                                 id: 'cosmoshub:tokens__native:ATOM',
    //                                 chain: 'cosmoshub',
    //                                 address: 'uatom',
    //                             },
    //                             {
    //                                 name: 'swapDirection',
    //                                 disabled: true,
    //                             },
    //                         ],
    //                     },
    //                     {
    //                         id: 'osmo-to-stars',
    //                         name: 'OSMO to STARS',
    //                         type: 'operation',
    //                         operationType: 'swap',
    //                         moduleType: 'superSwap',
    //                         paramsInterface: 'ISwapParams',
    //                         layoutComponent: 'SuperSwap',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'osmosis',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'osmosis:tokens__native:OSMO',
    //                                 chain: 'osmosis',
    //                                 address: 'uosmo',
    //                             },
    //                             {
    //                                 name: 'dstNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'stargaze',
    //                             },
    //                             {
    //                                 name: 'dstToken',
    //                                 disabled: true,
    //                                 id: 'stargaze:tokens__native:STARS',
    //                                 chain: 'stargaze',
    //                                 address: 'ustars',
    //                             },
    //                             {
    //                                 name: 'swapDirection',
    //                                 disabled: true,
    //                             },
    //                         ],
    //                     },
    //                 ],
    //             },
    //             {
    //                 id: 'stake-to-citadel-one',
    //                 name: 'Stake to the Citadel.one',
    //                 type: 'recipe',
    //                 operationType: 'stake',
    //                 moduleType: 'stake',
    //                 paramsInterface: 'IStakeParams',
    //                 layoutComponent: 'StakeLayout',
    //                 operations: [
    //                     {
    //                         id: 'stake-atom',
    //                         name: 'Stake ATOM',
    //                         type: 'operation',
    //                         operationType: 'stake',
    //                         moduleType: 'stake',
    //                         paramsInterface: 'IStakeParams',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'cosmoshub',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'cosmoshub:tokens__native:ATOM',
    //                                 chain: 'cosmoshub',
    //                                 address: 'uatom',
    //                             },
    //                             {
    //                                 name: 'receiverAddress',
    //                                 type: 'address',
    //                                 disabled: true,
    //                                 address: 'cosmosvaloper1lzhlnpahvznwfv4jmay2tgaha5kmz5qxerarrl',
    //                             },
    //                             {
    //                                 name: 'memo',
    //                                 type: 'string',
    //                                 disabled: true,
    //                                 memo: 'Stake to the Citadel.one validator | From zomet.app',
    //                             },
    //                         ],
    //                     },
    //                     {
    //                         id: 'stake-osmo',
    //                         name: 'Stake OSMO',
    //                         type: 'operation',
    //                         operationType: 'stake',
    //                         moduleType: 'stake',
    //                         paramsInterface: 'IStakeParams',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'osmosis',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'osmosis:tokens__native:OSMO',
    //                                 chain: 'osmosis',
    //                                 address: 'uosmo',
    //                             },
    //                             {
    //                                 name: 'receiverAddress',
    //                                 type: 'address',
    //                                 disabled: true,
    //                                 address: 'osmovaloper1lzhlnpahvznwfv4jmay2tgaha5kmz5qxwmj9we',
    //                             },
    //                             {
    //                                 name: 'memo',
    //                                 type: 'string',
    //                                 disabled: true,
    //                                 memo: 'Stake to the Citadel.one validator | From zomet.app',
    //                             },
    //                         ],
    //                     },
    //                     {
    //                         id: 'stake-stars',
    //                         name: 'Stake STARS',
    //                         type: 'operation',
    //                         operationType: 'stake',
    //                         moduleType: 'stake',
    //                         paramsInterface: 'IStakeParams',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'stargaze',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'stargaze:tokens__native:STARS',
    //                                 chain: 'stargaze',
    //                                 address: 'ustars',
    //                             },
    //                             {
    //                                 name: 'receiverAddress',
    //                                 type: 'address',
    //                                 disabled: true,
    //                                 address: 'starsvaloper1qv2tdjma7dcg6jmgawwd0aajjcx89rqca0cqgr',
    //                             },
    //                             {
    //                                 name: 'memo',
    //                                 type: 'string',
    //                                 disabled: true,
    //                                 memo: 'Stake to the Citadel.one validator | From zomet.app',
    //                             },
    //                         ],
    //                     },
    //                 ],
    //             },
    //         ],
    //     },
    // },
    // {
    //     id: 'deFi-strategy-60%-apy',
    //     name: 'DeFi Strategy - 60% APY',
    //     description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    //     logoURI: 'https://',
    //     wallpaper: '',
    //     type: 'airdrop',
    //     ecosystems: ['Cosmos'],
    //     minAmount: null,
    //     tags: ['best', 'airdrop'],
    //     author: {
    //         name: 'Zomet',
    //         avatar: 'https://zomet-logo.png',
    //     },
    //     recipe: {
    //         id: 'evm-osmosis-citadel-one-stake',
    //         operations: [
    //             {
    //                 id: 'bridge-eth-to-osmo',
    //                 name: 'Bridge Tokens to COSMOS (Osmosis)',
    //                 type: 'operation',
    //                 moduleType: 'superSwap',
    //                 operationType: 'bridge',
    //                 paramsInterface: 'IBridgeParams',
    //                 layoutComponent: 'SuperSwap',
    //                 skipConditions: [
    //                     {
    //                         name: 'srcNetwork',
    //                         value: 'osmosis',
    //                     },
    //                     {
    //                         name: 'srcToken',
    //                         value: 'osmosis:tokens__native:OSMO',
    //                     },
    //                 ],
    //                 params: [
    //                     {
    //                         name: 'srcNetwork',
    //                         disabled: false,
    //                         ecosystem: 'EVM',
    //                         chainId: 1,
    //                     },
    //                     {
    //                         name: 'srcToken',
    //                         disabled: false,
    //                         chain: 'eth',
    //                         id: 'eth:tokens__native:ETH',
    //                     },
    //                     {
    //                         name: 'dstNetwork',
    //                         disabled: true,
    //                         ecosystem: 'COSMOS',
    //                         chainId: 'osmosis',
    //                     },
    //                     {
    //                         name: 'dstToken',
    //                         disabled: true,
    //                         id: 'osmosis:tokens__native:OSMO',
    //                         chain: 'osmosis',
    //                     },
    //                     {
    //                         name: 'swapDirection',
    //                         disabled: true,
    //                     },
    //                 ],
    //             },
    //             {
    //                 id: 'swap-osmo-to-tokens',
    //                 name: 'Swap OSMO, ATOM, STARS',
    //                 type: 'recipe',
    //                 operationType: 'swap',
    //                 moduleType: 'superSwap',
    //                 paramsInterface: 'ISwapParams',
    //                 layoutComponent: 'SuperSwap',
    //                 operations: [
    //                     {
    //                         id: 'osmo-to-atom',
    //                         name: 'OSMO to ATOM',
    //                         type: 'operation',
    //                         operationType: 'swap',
    //                         moduleType: 'superSwap',
    //                         paramsInterface: 'ISwapParams',
    //                         layoutComponent: 'SuperSwap',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'osmosis',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'osmosis:tokens__native:OSMO',
    //                                 chain: 'osmosis',
    //                                 address: 'uosmo',
    //                             },
    //                             {
    //                                 name: 'dstNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'cosmoshub',
    //                             },
    //                             {
    //                                 name: 'dstToken',
    //                                 disabled: true,
    //                                 id: 'cosmoshub:tokens__native:ATOM',
    //                                 chain: 'cosmoshub',
    //                                 address: 'uatom',
    //                             },
    //                             {
    //                                 name: 'swapDirection',
    //                                 disabled: true,
    //                             },
    //                         ],
    //                     },
    //                     {
    //                         id: 'osmo-to-stars',
    //                         name: 'OSMO to STARS',
    //                         type: 'operation',
    //                         operationType: 'swap',
    //                         moduleType: 'superSwap',
    //                         paramsInterface: 'ISwapParams',
    //                         layoutComponent: 'SuperSwap',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'osmosis',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'osmosis:tokens__native:OSMO',
    //                                 chain: 'osmosis',
    //                                 address: 'uosmo',
    //                             },
    //                             {
    //                                 name: 'dstNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'stargaze',
    //                             },
    //                             {
    //                                 name: 'dstToken',
    //                                 disabled: true,
    //                                 id: 'stargaze:tokens__native:STARS',
    //                                 chain: 'stargaze',
    //                                 address: 'ustars',
    //                             },
    //                             {
    //                                 name: 'swapDirection',
    //                                 disabled: true,
    //                             },
    //                         ],
    //                     },
    //                 ],
    //             },
    //             {
    //                 id: 'stake-to-citadel-one',
    //                 name: 'Stake to the Citadel.one',
    //                 type: 'recipe',
    //                 operationType: 'stake',
    //                 moduleType: 'stake',
    //                 paramsInterface: 'IStakeParams',
    //                 layoutComponent: 'StakeLayout',
    //                 operations: [
    //                     {
    //                         id: 'stake-atom',
    //                         name: 'Stake ATOM',
    //                         type: 'operation',
    //                         operationType: 'stake',
    //                         moduleType: 'stake',
    //                         paramsInterface: 'IStakeParams',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'cosmoshub',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'cosmoshub:tokens__native:ATOM',
    //                                 chain: 'cosmoshub',
    //                                 address: 'uatom',
    //                             },
    //                             {
    //                                 name: 'receiverAddress',
    //                                 type: 'address',
    //                                 disabled: true,
    //                                 address: 'cosmosvaloper1lzhlnpahvznwfv4jmay2tgaha5kmz5qxerarrl',
    //                             },
    //                             {
    //                                 name: 'memo',
    //                                 type: 'string',
    //                                 disabled: true,
    //                                 memo: 'Stake to the Citadel.one validator | From zomet.app',
    //                             },
    //                         ],
    //                     },
    //                     {
    //                         id: 'stake-osmo',
    //                         name: 'Stake OSMO',
    //                         type: 'operation',
    //                         operationType: 'stake',
    //                         moduleType: 'stake',
    //                         paramsInterface: 'IStakeParams',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'osmosis',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'osmosis:tokens__native:OSMO',
    //                                 chain: 'osmosis',
    //                                 address: 'uosmo',
    //                             },
    //                             {
    //                                 name: 'receiverAddress',
    //                                 type: 'address',
    //                                 disabled: true,
    //                                 address: 'osmovaloper1lzhlnpahvznwfv4jmay2tgaha5kmz5qxwmj9we',
    //                             },
    //                             {
    //                                 name: 'memo',
    //                                 type: 'string',
    //                                 disabled: true,
    //                                 memo: 'Stake to the Citadel.one validator | From zomet.app',
    //                             },
    //                         ],
    //                     },
    //                     {
    //                         id: 'stake-stars',
    //                         name: 'Stake STARS',
    //                         type: 'operation',
    //                         operationType: 'stake',
    //                         moduleType: 'stake',
    //                         paramsInterface: 'IStakeParams',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'stargaze',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'stargaze:tokens__native:STARS',
    //                                 chain: 'stargaze',
    //                                 address: 'ustars',
    //                             },
    //                             {
    //                                 name: 'receiverAddress',
    //                                 type: 'address',
    //                                 disabled: true,
    //                                 address: 'starsvaloper1qv2tdjma7dcg6jmgawwd0aajjcx89rqca0cqgr',
    //                             },
    //                             {
    //                                 name: 'memo',
    //                                 type: 'string',
    //                                 disabled: true,
    //                                 memo: 'Stake to the Citadel.one validator | From zomet.app',
    //                             },
    //                         ],
    //                     },
    //                 ],
    //             },
    //         ],
    //     },
    // },
    // {
    //     id: 'mint-bad-kids',
    //     name: 'Mint Bad Kids',
    //     description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    //     logoURI: 'https://',
    //     wallpaper: '',
    //     type: 'airdrop',
    //     ecosystems: ['EVM', 'Cosmos'],
    //     minAmount: {
    //         value: 1,
    //         currency: 'ATOM',
    //     },
    //     tags: ['best', 'pool'],
    //     author: {
    //         name: 'Zomet',
    //         avatar: 'https://zomet-logo.png',
    //     },
    //     recipe: {
    //         id: 'evm-osmosis-citadel-one-stake',
    //         operations: [
    //             {
    //                 id: 'bridge-eth-to-osmo',
    //                 name: 'Bridge Tokens to COSMOS (Osmosis)',
    //                 type: 'operation',
    //                 moduleType: 'superSwap',
    //                 operationType: 'bridge',
    //                 paramsInterface: 'IBridgeParams',
    //                 layoutComponent: 'SuperSwap',
    //                 skipConditions: [
    //                     {
    //                         name: 'srcNetwork',
    //                         value: 'osmosis',
    //                     },
    //                     {
    //                         name: 'srcToken',
    //                         value: 'osmosis:tokens__native:OSMO',
    //                     },
    //                 ],
    //                 params: [
    //                     {
    //                         name: 'srcNetwork',
    //                         disabled: false,
    //                         ecosystem: 'EVM',
    //                         chainId: 1,
    //                     },
    //                     {
    //                         name: 'srcToken',
    //                         disabled: false,
    //                         chain: 'eth',
    //                         id: 'eth:tokens__native:ETH',
    //                     },
    //                     {
    //                         name: 'dstNetwork',
    //                         disabled: true,
    //                         ecosystem: 'COSMOS',
    //                         chainId: 'osmosis',
    //                     },
    //                     {
    //                         name: 'dstToken',
    //                         disabled: true,
    //                         id: 'osmosis:tokens__native:OSMO',
    //                         chain: 'osmosis',
    //                     },
    //                     {
    //                         name: 'swapDirection',
    //                         disabled: true,
    //                     },
    //                 ],
    //             },
    //             {
    //                 id: 'swap-osmo-to-tokens',
    //                 name: 'Swap OSMO, ATOM, STARS',
    //                 type: 'recipe',
    //                 operationType: 'swap',
    //                 moduleType: 'superSwap',
    //                 paramsInterface: 'ISwapParams',
    //                 layoutComponent: 'SuperSwap',
    //                 operations: [
    //                     {
    //                         id: 'osmo-to-atom',
    //                         name: 'OSMO to ATOM',
    //                         type: 'operation',
    //                         operationType: 'swap',
    //                         moduleType: 'superSwap',
    //                         paramsInterface: 'ISwapParams',
    //                         layoutComponent: 'SuperSwap',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'osmosis',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'osmosis:tokens__native:OSMO',
    //                                 chain: 'osmosis',
    //                                 address: 'uosmo',
    //                             },
    //                             {
    //                                 name: 'dstNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'cosmoshub',
    //                             },
    //                             {
    //                                 name: 'dstToken',
    //                                 disabled: true,
    //                                 id: 'cosmoshub:tokens__native:ATOM',
    //                                 chain: 'cosmoshub',
    //                                 address: 'uatom',
    //                             },
    //                             {
    //                                 name: 'swapDirection',
    //                                 disabled: true,
    //                             },
    //                         ],
    //                     },
    //                     {
    //                         id: 'osmo-to-stars',
    //                         name: 'OSMO to STARS',
    //                         type: 'operation',
    //                         operationType: 'swap',
    //                         moduleType: 'superSwap',
    //                         paramsInterface: 'ISwapParams',
    //                         layoutComponent: 'SuperSwap',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'osmosis',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'osmosis:tokens__native:OSMO',
    //                                 chain: 'osmosis',
    //                                 address: 'uosmo',
    //                             },
    //                             {
    //                                 name: 'dstNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'stargaze',
    //                             },
    //                             {
    //                                 name: 'dstToken',
    //                                 disabled: true,
    //                                 id: 'stargaze:tokens__native:STARS',
    //                                 chain: 'stargaze',
    //                                 address: 'ustars',
    //                             },
    //                             {
    //                                 name: 'swapDirection',
    //                                 disabled: true,
    //                             },
    //                         ],
    //                     },
    //                 ],
    //             },
    //             {
    //                 id: 'stake-to-citadel-one',
    //                 name: 'Stake to the Citadel.one',
    //                 type: 'recipe',
    //                 operationType: 'stake',
    //                 moduleType: 'stake',
    //                 paramsInterface: 'IStakeParams',
    //                 layoutComponent: 'StakeLayout',
    //                 operations: [
    //                     {
    //                         id: 'stake-atom',
    //                         name: 'Stake ATOM',
    //                         type: 'operation',
    //                         operationType: 'stake',
    //                         moduleType: 'stake',
    //                         paramsInterface: 'IStakeParams',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'cosmoshub',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'cosmoshub:tokens__native:ATOM',
    //                                 chain: 'cosmoshub',
    //                                 address: 'uatom',
    //                             },
    //                             {
    //                                 name: 'receiverAddress',
    //                                 type: 'address',
    //                                 disabled: true,
    //                                 address: 'cosmosvaloper1lzhlnpahvznwfv4jmay2tgaha5kmz5qxerarrl',
    //                             },
    //                             {
    //                                 name: 'memo',
    //                                 type: 'string',
    //                                 disabled: true,
    //                                 memo: 'Stake to the Citadel.one validator | From zomet.app',
    //                             },
    //                         ],
    //                     },
    //                     {
    //                         id: 'stake-osmo',
    //                         name: 'Stake OSMO',
    //                         type: 'operation',
    //                         operationType: 'stake',
    //                         moduleType: 'stake',
    //                         paramsInterface: 'IStakeParams',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'osmosis',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'osmosis:tokens__native:OSMO',
    //                                 chain: 'osmosis',
    //                                 address: 'uosmo',
    //                             },
    //                             {
    //                                 name: 'receiverAddress',
    //                                 type: 'address',
    //                                 disabled: true,
    //                                 address: 'osmovaloper1lzhlnpahvznwfv4jmay2tgaha5kmz5qxwmj9we',
    //                             },
    //                             {
    //                                 name: 'memo',
    //                                 type: 'string',
    //                                 disabled: true,
    //                                 memo: 'Stake to the Citadel.one validator | From zomet.app',
    //                             },
    //                         ],
    //                     },
    //                     {
    //                         id: 'stake-stars',
    //                         name: 'Stake STARS',
    //                         type: 'operation',
    //                         operationType: 'stake',
    //                         moduleType: 'stake',
    //                         paramsInterface: 'IStakeParams',
    //                         params: [
    //                             {
    //                                 name: 'srcNetwork',
    //                                 disabled: true,
    //                                 ecosystem: 'COSMOS',
    //                                 chainId: 'stargaze',
    //                             },
    //                             {
    //                                 name: 'srcToken',
    //                                 disabled: true,
    //                                 id: 'stargaze:tokens__native:STARS',
    //                                 chain: 'stargaze',
    //                                 address: 'ustars',
    //                             },
    //                             {
    //                                 name: 'receiverAddress',
    //                                 type: 'address',
    //                                 disabled: true,
    //                                 address: 'starsvaloper1qv2tdjma7dcg6jmgawwd0aajjcx89rqca0cqgr',
    //                             },
    //                             {
    //                                 name: 'memo',
    //                                 type: 'string',
    //                                 disabled: true,
    //                                 memo: 'Stake to the Citadel.one validator | From zomet.app',
    //                             },
    //                         ],
    //                     },
    //                 ],
    //             },
    //         ],
    //     },
    // },
];
