export const STATUSES = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
    REJECTED: 'REJECTED',
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN PROGRESS',
};

export const TRANSACTION_TYPES = {
    TRANSFER: 'TRANSFER',
    SIGN: 'SIGN',
    DEX: 'SWAP',
    BRIDGE: 'BRIDGE',
    APPROVE: 'APPROVE',
};
