export const SET_ADAPTER_BY_ECOSYSTEM = 'SET_ADAPTER_BY_ECOSYSTEM';
export const UPDATE_ADAPTER_BY_ECOSYSTEM = 'UPDATE_ADAPTER_BY_ECOSYSTEM';

export const SET_WALLET = 'SET_WALLET';

export const SET_WALLETS_MODULE = 'SET_WALLETS_MODULE';

export const DISCONNECT_WALLET = 'DISCONNECT_WALLET';
export const DISCONNECT_ALL_WALLETS = 'DISCONNECT_ALL_WALLETS';

export const SWITCH_ECOSYSTEM = 'SWITCH_ECOSYSTEM';

export const SET_MODAL_STATE = 'SET_MODAL_STATE';
export const SET_IS_CONNECTING = 'SET_IS_CONNECTING';
