export const BALANCES_TYPES = {
    ALL: 'ALL',
    PENDING: 'PENDING_REWARD',
    FUTURES: 'FUTURES',
    LEVERAGE_POSITION: 'LEVERAGE_POSITION',
    BORROW: 'BORROW',
    BORROW_AND_LENDING: 'BORROW_AND_LENDING',
    DEPOSIT_COLLATERAL: 'DEPOSIT_COLLATERAL',
};
