module.exports = [
    {
        name: 'Ethereum Mainnet',
        chain: 'ETH',
        icon: 'ethereum',
        rpc: ['https://api.mycryptoapi.com/eth', 'https://cloudflare-eth.com', 'https://ethereum.publicnode.com'],
        features: [
            {
                name: 'EIP155',
            },
            {
                name: 'EIP1559',
            },
        ],
        faucets: [],
        nativeCurrency: {
            name: 'Ether',
            symbol: 'ETH',
            decimals: 18,
        },
        infoURL: 'https://ethereum.org',
        shortName: 'eth',
        chainId: 1,
        networkId: 1,
        slip44: 60,
        ens: {
            registry: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e',
        },
        explorers: [
            {
                name: 'etherscan',
                url: 'https://etherscan.io',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Ubiq',
        chain: 'UBQ',
        rpc: ['https://rpc.octano.dev', 'https://pyrus2.ubiqscan.io'],
        faucets: [],
        nativeCurrency: {
            name: 'Ubiq Ether',
            symbol: 'UBQ',
            decimals: 18,
        },
        infoURL: 'https://ubiqsmart.com',
        shortName: 'ubq',
        chainId: 8,
        networkId: 8,
        slip44: 108,
        explorers: [
            {
                name: 'ubiqscan',
                url: 'https://ubiqscan.io',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Optimism',
        chain: 'ETH',
        rpc: ['https://mainnet.optimism.io/'],
        faucets: [],
        nativeCurrency: {
            name: 'Ether',
            symbol: 'ETH',
            decimals: 18,
        },
        infoURL: 'https://optimism.io',
        shortName: 'oeth',
        chainId: 10,
        networkId: 10,
        explorers: [
            {
                name: 'etherscan',
                url: 'https://optimistic.etherscan.io',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Songbird Canary-Network',
        chain: 'SGB',
        icon: 'songbird',
        rpc: [
            'https://songbird-api.flare.network/ext/C/rpc',
            'https://sgb.ftso.com.au/ext/bc/C/rpc',
            'https://sgb.lightft.so/rpc',
            'https://sgb-rpc.ftso.eu',
        ],
        faucets: [],
        nativeCurrency: {
            name: 'Songbird',
            symbol: 'SGB',
            decimals: 18,
        },
        infoURL: 'https://flare.xyz',
        shortName: 'sgb',
        chainId: 19,
        networkId: 19,
        explorers: [
            {
                name: 'blockscout',
                url: 'https://songbird-explorer.flare.network',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Elastos Smart Chain',
        chain: 'ETH',
        rpc: ['https://api.elastos.io/eth'],
        faucets: ['https://faucet.elastos.org/'],
        nativeCurrency: {
            name: 'Elastos',
            symbol: 'ELA',
            decimals: 18,
        },
        infoURL: 'https://www.elastos.org/',
        shortName: 'esc',
        chainId: 20,
        networkId: 20,
        explorers: [
            {
                name: 'elastos esc explorer',
                url: 'https://esc.elastos.io',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'KardiaChain Mainnet',
        chain: 'KAI',
        icon: 'kardiachain',
        rpc: ['https://rpc.kardiachain.io'],
        faucets: [],
        nativeCurrency: {
            name: 'KardiaChain',
            symbol: 'KAI',
            decimals: 18,
        },
        infoURL: 'https://kardiachain.io',
        shortName: 'kardiachain',
        chainId: 24,
        networkId: 0,
        redFlags: ['reusedChainId'],
    },
    {
        name: 'Cronos Mainnet Beta',
        chain: 'CRO',
        rpc: ['https://evm.cronos.org', 'https://cronos-evm.publicnode.com'],
        features: [
            {
                name: 'EIP1559',
            },
        ],
        faucets: [],
        nativeCurrency: {
            name: 'Cronos',
            symbol: 'CRO',
            decimals: 18,
        },
        infoURL: 'https://cronos.org/',
        shortName: 'cro',
        chainId: 25,
        networkId: 25,
        explorers: [
            {
                name: 'Cronos Explorer',
                url: 'https://cronoscan.com',
                standard: 'none',
            },
        ],
    },
    {
        name: 'RSK Mainnet',
        chain: 'RSK',
        rpc: ['https://public-node.rsk.co', 'https://mycrypto.rsk.co'],
        faucets: ['https://faucet.rsk.co/'],
        nativeCurrency: {
            name: 'Smart Bitcoin',
            symbol: 'RBTC',
            decimals: 18,
        },
        infoURL: 'https://rsk.co',
        shortName: 'rsk',
        chainId: 30,
        networkId: 30,
        slip44: 137,
        explorers: [
            {
                name: 'RSK Explorer',
                url: 'https://explorer.rsk.co',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Telos EVM Mainnet',
        chain: 'TLOS',
        rpc: ['https://mainnet.telos.net/evm'],
        faucets: [],
        nativeCurrency: {
            name: 'Telos',
            symbol: 'TLOS',
            decimals: 18,
        },
        infoURL: 'https://telos.net',
        shortName: 'TelosEVM',
        chainId: 40,
        networkId: 40,
        explorers: [
            {
                name: 'teloscan',
                url: 'https://teloscan.io',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'XinFin XDC Network',
        chain: 'XDC',
        rpc: [
            'https://erpc.xinfin.network',
            'https://rpc.xinfin.network',
            'https://rpc1.xinfin.network',
            'https://rpc-xdc.icecreamswap.com',
        ],
        faucets: [],
        nativeCurrency: {
            name: 'XinFin',
            symbol: 'XDC',
            decimals: 18,
        },
        infoURL: 'https://xinfin.org',
        shortName: 'xdc',
        chainId: 50,
        networkId: 50,
        icon: 'xdc',
        explorers: [
            {
                name: 'xdcscan',
                url: 'https://xdcscan.io',
                icon: 'blocksscan',
                standard: 'EIP3091',
            },
            {
                name: 'blocksscan',
                url: 'https://xdc.blocksscan.io',
                icon: 'blocksscan',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'CoinEx Smart Chain Mainnet',
        chain: 'CSC',
        rpc: ['https://rpc.coinex.net'],
        faucets: [],
        nativeCurrency: {
            name: 'CoinEx Chain Native Token',
            symbol: 'cet',
            decimals: 18,
        },
        infoURL: 'https://www.coinex.org/',
        shortName: 'cet',
        chainId: 52,
        networkId: 52,
        explorers: [
            {
                name: 'coinexscan',
                url: 'https://www.coinex.net',
                standard: 'none',
            },
        ],
    },
    {
        name: 'Zyx Mainnet',
        chain: 'ZYX',
        rpc: [
            'https://rpc-1.zyx.network/',
            'https://rpc-2.zyx.network/',
            'https://rpc-3.zyx.network/',
            'https://rpc-4.zyx.network/',
            'https://rpc-5.zyx.network/',
            'https://rpc-6.zyx.network/',
        ],
        faucets: [],
        nativeCurrency: {
            name: 'Zyx',
            symbol: 'ZYX',
            decimals: 18,
        },
        infoURL: 'https://zyx.network/',
        shortName: 'ZYX',
        chainId: 55,
        networkId: 55,
        explorers: [
            {
                name: 'zyxscan',
                url: 'https://zyxscan.com',
                standard: 'none',
            },
        ],
    },
    {
        name: 'Binance Smart Chain Mainnet',
        chain: 'BSC',
        rpc: [
            'https://bsc-dataseed1.binance.org',
            'https://bsc-dataseed2.binance.org',
            'https://bsc-dataseed3.binance.org',
            'https://bsc-dataseed4.binance.org',
            'https://bsc-dataseed1.defibit.io',
            'https://bsc-dataseed2.defibit.io',
            'https://bsc-dataseed3.defibit.io',
            'https://bsc-dataseed4.defibit.io',
            'https://bsc-dataseed1.ninicoin.io',
            'https://bsc-dataseed2.ninicoin.io',
            'https://bsc-dataseed3.ninicoin.io',
            'https://bsc-dataseed4.ninicoin.io',
            'https://bsc.publicnode.com',
            'wss://bsc-ws-node.nariox.org',
        ],
        faucets: ['https://free-online-app.com/faucet-for-eth-evm-chains/'],
        nativeCurrency: {
            name: 'Binance Chain Native Token',
            symbol: 'BNB',
            decimals: 18,
        },
        infoURL: 'https://www.binance.org',
        shortName: 'bnb',
        chainId: 56,
        networkId: 56,
        slip44: 714,
        explorers: [
            {
                name: 'bscscan',
                url: 'https://bscscan.com',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Syscoin Mainnet',
        chain: 'SYS',
        rpc: ['https://rpc.syscoin.org', 'wss://rpc.syscoin.org/wss'],
        faucets: ['https://faucet.syscoin.org'],
        nativeCurrency: {
            name: 'Syscoin',
            symbol: 'SYS',
            decimals: 18,
        },
        infoURL: 'https://www.syscoin.org',
        shortName: 'sys',
        chainId: 57,
        networkId: 57,
        explorers: [
            {
                name: 'Syscoin Block Explorer',
                url: 'https://explorer.syscoin.org',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'GoChain',
        chain: 'GO',
        rpc: ['https://rpc.gochain.io'],
        faucets: ['https://free-online-app.com/faucet-for-eth-evm-chains/'],
        nativeCurrency: {
            name: 'GoChain Ether',
            symbol: 'GO',
            decimals: 18,
        },
        infoURL: 'https://gochain.io',
        shortName: 'go',
        chainId: 60,
        networkId: 60,
        slip44: 6060,
        explorers: [
            {
                name: 'GoChain Explorer',
                url: 'https://explorer.gochain.io',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Ethereum Classic Mainnet',
        chain: 'ETC',
        rpc: ['https://www.ethercluster.com/etc'],
        faucets: ['https://free-online-app.com/faucet-for-eth-evm-chains/?'],
        nativeCurrency: {
            name: 'Ethereum Classic Ether',
            symbol: 'ETC',
            decimals: 18,
        },
        infoURL: 'https://ethereumclassic.org',
        shortName: 'etc',
        chainId: 61,
        networkId: 1,
        slip44: 61,
        explorers: [
            {
                name: 'blockscout',
                url: 'https://blockscout.com/etc/mainnet',
                standard: 'none',
            },
        ],
    },
    {
        name: 'OKXChain Mainnet',
        chain: 'okxchain',
        rpc: ['https://exchainrpc.okex.org', 'https://okc-mainnet.gateway.pokt.network/v1/lb/6275309bea1b320039c893ff'],
        faucets: ['https://free-online-app.com/faucet-for-eth-evm-chains/?'],
        nativeCurrency: {
            name: 'OKXChain Global Utility Token',
            symbol: 'OKT',
            decimals: 18,
        },
        infoURL: 'https://www.okex.com/okc',
        shortName: 'okt',
        chainId: 66,
        networkId: 66,
        explorers: [
            {
                name: 'OKLink',
                url: 'https://www.oklink.com/en/okc',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Hoo Smart Chain',
        chain: 'HSC',
        rpc: [
            'https://http-mainnet.hoosmartchain.com',
            'https://http-mainnet2.hoosmartchain.com',
            'wss://ws-mainnet.hoosmartchain.com',
            'wss://ws-mainnet2.hoosmartchain.com',
        ],
        faucets: [],
        nativeCurrency: {
            name: 'Hoo Smart Chain Native Token',
            symbol: 'HOO',
            decimals: 18,
        },
        infoURL: 'https://www.hoosmartchain.com',
        shortName: 'hsc',
        chainId: 70,
        networkId: 70,
        slip44: 1170,
        explorers: [
            {
                name: 'hooscan',
                url: 'https://www.hooscan.com',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Meter Mainnet',
        chain: 'METER',
        rpc: ['https://rpc.meter.io'],
        faucets: ['https://faucet.meter.io'],
        nativeCurrency: {
            name: 'Meter',
            symbol: 'MTR',
            decimals: 18,
        },
        infoURL: 'https://www.meter.io',
        shortName: 'Meter',
        chainId: 82,
        networkId: 82,
        explorers: [
            {
                name: 'Meter Mainnet Scan',
                url: 'https://scan.meter.io',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Nova Network',
        chain: 'NNW',
        icon: 'novanetwork',
        rpc: ['https://connect.novanetwork.io', 'https://0x57.redjackstudio.com', 'https://rpc.novanetwork.io:9070'],
        faucets: [],
        nativeCurrency: {
            name: 'Supernova',
            symbol: 'SNT',
            decimals: 18,
        },
        infoURL: 'https://novanetwork.io',
        shortName: 'nnw',
        chainId: 87,
        networkId: 87,
        explorers: [
            {
                name: 'novanetwork',
                url: 'https://explorer.novanetwork.io',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'TomoChain',
        chain: 'TOMO',
        rpc: ['https://rpc.tomochain.com'],
        faucets: [],
        nativeCurrency: {
            name: 'TomoChain',
            symbol: 'TOMO',
            decimals: 18,
        },
        infoURL: 'https://tomochain.com',
        shortName: 'tomo',
        chainId: 88,
        networkId: 88,
        slip44: 889,
    },
    {
        name: 'Gnosis',
        chain: 'GNO',
        icon: 'gnosis',
        rpc: [
            'https://rpc.gnosischain.com',
            'https://rpc.ankr.com/gnosis',
            'https://gnosischain-rpc.gateway.pokt.network',
            'https://gnosis-mainnet.public.blastapi.io',
            'wss://rpc.gnosischain.com/wss',
        ],
        faucets: [
            'https://gnosisfaucet.com',
            'https://faucet.gimlu.com/gnosis',
            'https://stakely.io/faucet/gnosis-chain-xdai',
            'https://faucet.prussia.dev/xdai',
        ],
        nativeCurrency: {
            name: 'xDAI',
            symbol: 'xDAI',
            decimals: 18,
        },
        infoURL: 'https://docs.gnosischain.com',
        shortName: 'gno',
        chainId: 100,
        networkId: 100,
        slip44: 700,
        explorers: [
            {
                name: 'gnosisscan',
                url: 'https://gnosisscan.io',
                standard: 'EIP3091',
            },
            {
                name: 'blockscout',
                url: 'https://blockscout.com/xdai/mainnet',
                icon: 'blockscout',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Velas EVM Mainnet',
        chain: 'Velas',
        icon: 'velas',
        rpc: ['https://evmexplorer.velas.com/rpc', 'https://explorer.velas.com/rpc'],
        faucets: [],
        nativeCurrency: {
            name: 'Velas',
            symbol: 'VLX',
            decimals: 18,
        },
        infoURL: 'https://velas.com',
        shortName: 'vlx',
        chainId: 106,
        networkId: 106,
        explorers: [
            {
                name: 'Velas Explorer',
                url: 'https://evmexplorer.velas.com',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'ThunderCore Mainnet',
        chain: 'TT',
        rpc: ['https://mainnet-rpc.thundercore.com', 'https://mainnet-rpc.thundertoken.net', 'https://mainnet-rpc.thundercore.io'],
        faucets: ['https://faucet.thundercore.com'],
        nativeCurrency: {
            name: 'ThunderCore Token',
            symbol: 'TT',
            decimals: 18,
        },
        infoURL: 'https://thundercore.com',
        shortName: 'TT',
        chainId: 108,
        networkId: 108,
        slip44: 1001,
        explorers: [
            {
                name: 'thundercore-viewblock',
                url: 'https://viewblock.io/thundercore',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Fuse Mainnet',
        chain: 'FUSE',
        rpc: ['https://rpc.fuse.io'],
        faucets: [],
        nativeCurrency: {
            name: 'Fuse',
            symbol: 'FUSE',
            decimals: 18,
        },
        infoURL: 'https://fuse.io/',
        shortName: 'fuse',
        chainId: 122,
        networkId: 122,
    },
    {
        name: 'Huobi ECO Chain Mainnet',
        chain: 'Heco',
        rpc: ['https://http-mainnet.hecochain.com', 'wss://ws-mainnet.hecochain.com'],
        faucets: ['https://free-online-app.com/faucet-for-eth-evm-chains/'],
        nativeCurrency: {
            name: 'Huobi ECO Chain Native Token',
            symbol: 'HT',
            decimals: 18,
        },
        infoURL: 'https://www.hecochain.com',
        shortName: 'heco',
        chainId: 128,
        networkId: 128,
        slip44: 1010,
        explorers: [
            {
                name: 'hecoinfo',
                url: 'https://hecoinfo.com',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Polygon Mainnet',
        chain: 'Polygon',
        icon: 'polygon',
        rpc: [
            'https://polygon-rpc.com/',
            'https://rpc-mainnet.matic.network',
            'https://matic-mainnet.chainstacklabs.com',
            'https://rpc-mainnet.maticvigil.com',
            'https://rpc-mainnet.matic.quiknode.pro',
            'https://matic-mainnet-full-rpc.bwarelabs.com',
            'https://polygon-bor.publicnode.com',
        ],
        faucets: [],
        nativeCurrency: {
            name: 'MATIC',
            symbol: 'MATIC',
            decimals: 18,
        },
        infoURL: 'https://polygon.technology/',
        shortName: 'matic',
        chainId: 137,
        networkId: 137,
        slip44: 966,
        explorers: [
            {
                name: 'polygonscan',
                url: 'https://polygonscan.com',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Arbitrum on xDai',
        chain: 'AOX',
        rpc: ['https://arbitrum.xdaichain.com/'],
        faucets: [],
        nativeCurrency: {
            name: 'xDAI',
            symbol: 'xDAI',
            decimals: 18,
        },
        infoURL: 'https://xdaichain.com',
        shortName: 'aox',
        chainId: 200,
        networkId: 200,
        explorers: [
            {
                name: 'blockscout',
                url: 'https://blockscout.com/xdai/arbitrum',
                standard: 'EIP3091',
            },
        ],
        parent: {
            chain: 'eip155-100',
            type: 'L2',
        },
    },
    {
        name: 'Energy Web Chain',
        chain: 'Energy Web Chain',
        rpc: ['https://rpc.energyweb.org', 'wss://rpc.energyweb.org/ws'],
        faucets: ['https://faucet.carbonswap.exchange', 'https://free-online-app.com/faucet-for-eth-evm-chains/'],
        nativeCurrency: {
            name: 'Energy Web Token',
            symbol: 'EWT',
            decimals: 18,
        },
        infoURL: 'https://energyweb.org',
        shortName: 'ewt',
        chainId: 246,
        networkId: 246,
        slip44: 246,
        explorers: [
            {
                name: 'blockscout',
                url: 'https://explorer.energyweb.org',
                standard: 'none',
            },
        ],
    },
    {
        name: 'Fantom Opera',
        chain: 'FTM',
        rpc: ['https://rpc.ftm.tools', 'https://fantom.publicnode.com'],
        faucets: ['https://free-online-app.com/faucet-for-eth-evm-chains/'],
        nativeCurrency: {
            name: 'Fantom',
            symbol: 'FTM',
            decimals: 18,
        },
        infoURL: 'https://fantom.foundation',
        shortName: 'ftm',
        chainId: 250,
        networkId: 250,
        icon: 'fantom',
        explorers: [
            {
                name: 'ftmscan',
                url: 'https://ftmscan.com',
                icon: 'ftmscan',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'High Performance Blockchain',
        chain: 'HPB',
        rpc: ['https://hpbnode.com', 'wss://ws.hpbnode.com'],
        faucets: ['https://myhpbwallet.com/'],
        nativeCurrency: {
            name: 'High Performance Blockchain Ether',
            symbol: 'HPB',
            decimals: 18,
        },
        infoURL: 'https://hpb.io',
        shortName: 'hpb',
        chainId: 269,
        networkId: 269,
        slip44: 269,
        explorers: [
            {
                name: 'hscan',
                url: 'https://hscan.org',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Boba Network',
        chain: 'ETH',
        rpc: ['https://mainnet.boba.network/'],
        faucets: [],
        nativeCurrency: {
            name: 'Ether',
            symbol: 'ETH',
            decimals: 18,
        },
        infoURL: 'https://boba.network',
        shortName: 'Boba',
        chainId: 288,
        networkId: 288,
        explorers: [
            {
                name: 'Bobascan',
                url: 'https://bobascan.com',
                standard: 'none',
            },
            {
                name: 'Blockscout',
                url: 'https://blockexplorer.boba.network',
                standard: 'none',
            },
        ],
        parent: {
            type: 'L2',
            chain: 'eip155-1',
            bridges: [
                {
                    url: 'https://gateway.boba.network',
                },
            ],
        },
    },
    {
        name: 'Omax Mainnet',
        chain: 'OMAX Chain',
        rpc: ['https://mainapi.omaxray.com'],
        faucets: ['https://faucet.omaxray.com/'],
        nativeCurrency: {
            name: 'OMAX COIN',
            symbol: 'OMAX',
            decimals: 18,
        },
        infoURL: 'https://www.omaxcoin.com/',
        shortName: 'omax',
        chainId: 311,
        networkId: 311,
        icon: 'omaxchain',
        explorers: [
            {
                name: 'Omax Chain Explorer',
                url: 'https://omaxray.com',
                icon: 'omaxray',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Filecoin - Mainnet',
        chain: 'FIL',
        icon: 'filecoin',
        rpc: ['https://api.node.glif.io/', 'https://rpc.ankr.com/filecoin', 'https://filecoin-mainnet.chainstacklabs.com/rpc/v1'],
        faucets: [],
        nativeCurrency: {
            name: 'filecoin',
            symbol: 'FIL',
            decimals: 18,
        },
        infoURL: 'https://filecoin.io',
        shortName: 'filecoin',
        chainId: 314,
        networkId: 314,
        slip44: 461,
        explorers: [
            {
                name: 'Filfox',
                url: 'https://filfox.info/en',
                standard: 'none',
            },
            {
                name: 'Beryx',
                url: 'https://beryx.zondax.ch',
                standard: 'none',
            },
            {
                name: 'Glif Explorer',
                url: 'https://explorer.glif.io',
                standard: 'EIP3091',
            },
            {
                name: 'Dev.storage',
                url: 'https://dev.storage',
                standard: 'none',
            },
            {
                name: 'Filscan',
                url: 'https://filscan.io',
                standard: 'none',
            },
            {
                name: 'Filscout',
                url: 'https://filscout.io/en',
                standard: 'none',
            },
        ],
    },
    {
        name: 'KCC Mainnet',
        chain: 'KCC',
        rpc: ['https://rpc-mainnet.kcc.network', 'https://kcc.mytokenpocket.vip', 'https://public-rpc.blockpi.io/http/kcc'],
        faucets: ['https://faucet.kcc.io/', 'https://free-online-app.com/faucet-for-eth-evm-chains/'],
        nativeCurrency: {
            name: 'KuCoin Token',
            symbol: 'KCS',
            decimals: 18,
        },
        infoURL: 'https://kcc.io',
        shortName: 'kcs',
        chainId: 321,
        networkId: 321,
        slip44: 641,
        explorers: [
            {
                name: 'KCC Explorer',
                url: 'https://explorer.kcc.io/en',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'zkSync Era Mainnet',
        chain: 'ETH',
        rpc: ['https://mainnet.era.zksync.io'],
        faucets: [],
        nativeCurrency: {
            name: 'Ether',
            symbol: 'ETH',
            decimals: 18,
        },
        infoURL: 'https://zksync.io/',
        shortName: 'zksync',
        chainId: 324,
        networkId: 324,
        icon: 'zksync-era',
        explorers: [
            {
                name: 'zkSync Era Block Explorer',
                url: 'https://explorer.zksync.io',
                icon: 'zksync-era',
                standard: 'EIP3091',
            },
        ],
        parent: {
            type: 'L2',
            chain: 'eip155-1',
            bridges: [
                {
                    url: 'https://bridge.zksync.io/',
                },
            ],
        },
    },
    {
        name: 'Shiden',
        chain: 'SDN',
        rpc: [
            'https://shiden.api.onfinality.io/public',
            'https://shiden-rpc.dwellir.com',
            'https://shiden.public.blastapi.io',
            'wss://shiden.api.onfinality.io/public-ws',
            'wss://shiden.public.blastapi.io',
            'wss://shiden-rpc.dwellir.com',
        ],
        faucets: [],
        nativeCurrency: {
            name: 'Shiden',
            symbol: 'SDN',
            decimals: 18,
        },
        infoURL: 'https://shiden.astar.network/',
        shortName: 'sdn',
        chainId: 336,
        networkId: 336,
        icon: 'shiden',
        explorers: [
            {
                name: 'subscan',
                url: 'https://shiden.subscan.io',
                standard: 'none',
                icon: 'subscan',
            },
        ],
    },
    {
        name: 'Theta Mainnet',
        chain: 'Theta',
        rpc: ['https://eth-rpc-api.thetatoken.org/rpc'],
        faucets: [],
        nativeCurrency: {
            name: 'Theta Fuel',
            symbol: 'TFUEL',
            decimals: 18,
        },
        infoURL: 'https://www.thetatoken.org/',
        shortName: 'theta-mainnet',
        chainId: 361,
        networkId: 361,
        explorers: [
            {
                name: 'Theta Mainnet Explorer',
                url: 'https://explorer.thetatoken.org',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'SX Network Mainnet',
        chain: 'SX',
        icon: 'SX',
        rpc: ['https://rpc.sx.technology'],
        faucets: [],
        nativeCurrency: {
            name: 'SX Network',
            symbol: 'SX',
            decimals: 18,
        },
        infoURL: 'https://www.sx.technology',
        shortName: 'SX',
        chainId: 416,
        networkId: 416,
        explorers: [
            {
                name: 'SX Network Explorer',
                url: 'https://explorer.sx.technology',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Candle',
        chain: 'Candle',
        rpc: ['https://candle-rpc.com/', 'https://rpc.cndlchain.com'],
        faucets: [],
        nativeCurrency: {
            name: 'CANDLE',
            symbol: 'CNDL',
            decimals: 18,
        },
        infoURL: 'https://candlelabs.org/',
        shortName: 'CNDL',
        chainId: 534,
        networkId: 534,
        slip44: 674,
        explorers: [
            {
                name: 'candleexplorer',
                url: 'https://candleexplorer.com',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Astar',
        chain: 'ASTR',
        rpc: ['https://rpc.astar.network:8545'],
        faucets: [],
        nativeCurrency: {
            name: 'Astar',
            symbol: 'ASTR',
            decimals: 18,
        },
        infoURL: 'https://astar.network/',
        shortName: 'astr',
        chainId: 592,
        networkId: 592,
        icon: 'astar',
        explorers: [
            {
                name: 'subscan',
                url: 'https://astar.subscan.io',
                standard: 'none',
                icon: 'subscan',
            },
        ],
    },
    {
        name: 'Callisto Mainnet',
        chain: 'CLO',
        rpc: ['https://rpc.callisto.network/'],
        faucets: [],
        nativeCurrency: {
            name: 'Callisto',
            symbol: 'CLO',
            decimals: 18,
        },
        infoURL: 'https://callisto.network',
        shortName: 'clo',
        chainId: 820,
        networkId: 1,
        slip44: 820,
    },
    {
        name: 'Wanchain',
        chain: 'WAN',
        rpc: ['https://gwan-ssl.wandevs.org:56891/'],
        faucets: [],
        nativeCurrency: {
            name: 'Wancoin',
            symbol: 'WAN',
            decimals: 18,
        },
        infoURL: 'https://www.wanscan.org',
        shortName: 'wan',
        chainId: 888,
        networkId: 888,
        slip44: 5718350,
    },
    {
        name: 'Metis Andromeda Mainnet',
        chain: 'ETH',
        rpc: ['https://andromeda.metis.io/?owner=1088'],
        faucets: [],
        nativeCurrency: {
            name: 'Metis',
            symbol: 'METIS',
            decimals: 18,
        },
        infoURL: 'https://www.metis.io',
        shortName: 'metis-andromeda',
        chainId: 1088,
        networkId: 1088,
        explorers: [
            {
                name: 'blockscout',
                url: 'https://andromeda-explorer.metis.io',
                standard: 'EIP3091',
            },
        ],
        parent: {
            type: 'L2',
            chain: 'eip155-1',
            bridges: [
                {
                    url: 'https://bridge.metis.io',
                },
            ],
        },
    },
    {
        name: 'Polygon zkEVM',
        title: 'Polygon zkEVM',
        chain: 'Polygon',
        rpc: ['https://zkevm-rpc.com'],
        faucets: [],
        nativeCurrency: {
            name: 'Ether',
            symbol: 'ETH',
            decimals: 18,
        },
        infoURL: 'https://polygon.technology/polygon-zkevm',
        shortName: 'zkevm',
        chainId: 1101,
        networkId: 1101,
        icon: 'zkevm',
        explorers: [
            {
                name: 'blockscout',
                url: 'https://zkevm.polygonscan.com',
                icon: 'zkevm',
                standard: 'EIP3091',
            },
        ],
        parent: {
            type: 'L2',
            chain: 'eip155-1',
            bridges: [
                {
                    url: 'https://bridge.zkevm-rpc.com',
                },
            ],
        },
    },
    {
        name: 'Core Blockchain Mainnet',
        chain: 'Core',
        icon: 'core',
        rpc: ['https://rpc.coredao.org/', 'https://rpc-core.icecreamswap.com'],
        faucets: [],
        nativeCurrency: {
            name: 'Core Blockchain Native Token',
            symbol: 'CORE',
            decimals: 18,
        },
        infoURL: 'https://www.coredao.org',
        shortName: 'core',
        chainId: 1116,
        networkId: 1116,
        explorers: [
            {
                name: 'Core Scan',
                url: 'https://scan.coredao.org',
                icon: 'core',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Ultron Mainnet',
        chain: 'Ultron',
        icon: 'ultron',
        rpc: ['https://ultron-rpc.net'],
        faucets: [],
        nativeCurrency: {
            name: 'Ultron',
            symbol: 'ULX',
            decimals: 18,
        },
        infoURL: 'https://ultron.foundation',
        shortName: 'UtronMainnet',
        chainId: 1231,
        networkId: 1231,
        explorers: [
            {
                name: 'Ultron Explorer',
                url: 'https://ulxscan.com',
                icon: 'ultron',
                standard: 'none',
            },
        ],
    },
    {
        name: 'Step Network',
        title: 'Step Main Network',
        chain: 'STEP',
        icon: 'step',
        rpc: ['https://rpc.step.network'],
        faucets: [],
        nativeCurrency: {
            name: 'FITFI',
            symbol: 'FITFI',
            decimals: 18,
        },
        infoURL: 'https://step.network',
        shortName: 'step',
        chainId: 1234,
        networkId: 1234,
        explorers: [
            {
                name: 'StepScan',
                url: 'https://stepscan.io',
                icon: 'step',
                standard: 'EIP3091',
            },
        ],
        parent: {
            type: 'L2',
            chain: 'eip155-43114',
            bridges: [
                {
                    url: 'https://bridge.step.network',
                },
            ],
        },
    },
    {
        name: 'Moonbeam',
        chain: 'MOON',
        rpc: ['https://rpc.api.moonbeam.network', 'wss://wss.api.moonbeam.network'],
        faucets: [],
        nativeCurrency: {
            name: 'Glimmer',
            symbol: 'GLMR',
            decimals: 18,
        },
        infoURL: 'https://moonbeam.network/networks/moonbeam/',
        shortName: 'mbeam',
        chainId: 1284,
        networkId: 1284,
        explorers: [
            {
                name: 'moonscan',
                url: 'https://moonbeam.moonscan.io',
                standard: 'none',
            },
        ],
    },
    {
        name: 'Moonriver',
        chain: 'MOON',
        rpc: ['https://rpc.api.moonriver.moonbeam.network', 'wss://wss.api.moonriver.moonbeam.network'],
        faucets: [],
        nativeCurrency: {
            name: 'Moonriver',
            symbol: 'MOVR',
            decimals: 18,
        },
        infoURL: 'https://moonbeam.network/networks/moonriver/',
        shortName: 'mriver',
        chainId: 1285,
        networkId: 1285,
        explorers: [
            {
                name: 'moonscan',
                url: 'https://moonriver.moonscan.io',
                standard: 'none',
            },
        ],
    },
    {
        name: 'Dogechain Mainnet',
        chain: 'DC',
        icon: 'dogechain',
        rpc: ['https://rpc.dogechain.dog', 'https://rpc01-sg.dogechain.dog', 'https://rpc.ankr.com/dogechain'],
        faucets: [],
        nativeCurrency: {
            name: 'Dogecoin',
            symbol: 'DOGE',
            decimals: 18,
        },
        infoURL: 'https://dogechain.dog',
        shortName: 'dc',
        chainId: 2000,
        networkId: 2000,
        explorers: [
            {
                name: 'dogechain explorer',
                url: 'https://explorer.dogechain.dog',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Kava EVM',
        chain: 'KAVA',
        rpc: ['https://evm.kava.io', 'https://evm2.kava.io', 'wss://wevm.kava.io', 'wss://wevm2.kava.io'],
        faucets: [],
        nativeCurrency: {
            name: 'Kava',
            symbol: 'KAVA',
            decimals: 18,
        },
        infoURL: 'https://www.kava.io',
        shortName: 'kava',
        chainId: 2222,
        networkId: 2222,
        icon: 'kava',
        explorers: [
            {
                name: 'Kava EVM Explorer',
                url: 'https://explorer.kava.io',
                standard: 'EIP3091',
                icon: 'kava',
            },
        ],
    },
    {
        name: 'IoTeX Network Mainnet',
        chain: 'iotex.io',
        rpc: ['https://babel-api.mainnet.iotex.io'],
        faucets: [],
        nativeCurrency: {
            name: 'IoTeX',
            symbol: 'IOTX',
            decimals: 18,
        },
        infoURL: 'https://iotex.io',
        shortName: 'iotex-mainnet',
        chainId: 4689,
        networkId: 4689,
        explorers: [
            {
                name: 'iotexscan',
                url: 'https://iotexscan.io',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Nahmii Mainnet',
        chain: 'Nahmii',
        rpc: ['https://l2.nahmii.io'],
        faucets: [],
        nativeCurrency: {
            name: 'Ether',
            symbol: 'ETH',
            decimals: 18,
        },
        infoURL: 'https://nahmii.io',
        shortName: 'Nahmii',
        chainId: 5551,
        networkId: 5551,
        icon: 'nahmii',
        explorers: [
            {
                name: 'Nahmii mainnet explorer',
                url: 'https://explorer.nahmii.io',
                icon: 'nahmii',
                standard: 'EIP3091',
            },
        ],
        parent: {
            type: 'L2',
            chain: 'eip155-1',
            bridges: [
                {
                    url: 'https://bridge.nahmii.io',
                },
            ],
        },
    },
    {
        name: 'Tomb Chain Mainnet',
        chain: 'Tomb Chain',
        rpc: ['https://rpc.tombchain.com/'],
        faucets: [],
        nativeCurrency: {
            name: 'Tomb',
            symbol: 'TOMB',
            decimals: 18,
        },
        infoURL: 'https://tombchain.com/',
        shortName: 'tombchain',
        chainId: 6969,
        networkId: 6969,
        explorers: [
            {
                name: 'tombscout',
                url: 'https://tombscout.com',
                standard: 'none',
            },
        ],
        parent: {
            type: 'L2',
            chain: 'eip155-250',
            bridges: [
                {
                    url: 'https://lif3.com/bridge',
                },
            ],
        },
    },
    {
        name: 'Canto',
        chain: 'Canto',
        rpc: ['https://canto.slingshot.finance', 'https://canto.neobase.one', 'https://mainnode.plexnode.org:8545'],
        faucets: [],
        nativeCurrency: {
            name: 'Canto',
            symbol: 'CANTO',
            decimals: 18,
        },
        infoURL: 'https://canto.io',
        shortName: 'canto',
        chainId: 7700,
        networkId: 7700,
        explorers: [
            {
                name: 'Canto EVM Explorer (Blockscout)',
                url: 'https://evm.explorer.canto.io',
                standard: 'none',
            },
            {
                name: 'Canto Cosmos Explorer',
                url: 'https://cosmos-explorers.neobase.one',
                standard: 'none',
            },
            {
                name: 'Canto EVM Explorer (Blockscout)',
                url: 'https://tuber.build',
                standard: 'none',
            },
        ],
    },
    {
        name: 'Klaytn Mainnet Cypress',
        chain: 'KLAY',
        rpc: ['https://public-node-api.klaytnapi.com/v1/cypress'],
        faucets: [],
        nativeCurrency: {
            name: 'KLAY',
            symbol: 'KLAY',
            decimals: 18,
        },
        infoURL: 'https://www.klaytn.com/',
        shortName: 'Cypress',
        chainId: 8217,
        networkId: 8217,
        slip44: 8217,
        explorers: [
            {
                name: 'Klaytnscope',
                url: 'https://scope.klaytn.com',
                standard: 'none',
            },
        ],
    },
    {
        name: 'Evmos',
        chain: 'Evmos',
        rpc: ['https://eth.bd.evmos.org:8545', 'https://evmos-evm.publicnode.com'],
        faucets: [],
        nativeCurrency: {
            name: 'Evmos',
            symbol: 'EVMOS',
            decimals: 18,
        },
        infoURL: 'https://evmos.org',
        shortName: 'evmos',
        chainId: 9001,
        networkId: 9001,
        icon: 'evmos',
        explorers: [
            {
                name: 'Evmos EVM Explorer (Escan)',
                url: 'https://escan.live',
                standard: 'none',
                icon: 'evmos',
            },
            {
                name: 'Evmos Cosmos Explorer (Mintscan)',
                url: 'https://www.mintscan.io/evmos',
                standard: 'none',
                icon: 'evmos',
            },
        ],
    },
    {
        name: 'Carbon EVM',
        chain: 'Carbon',
        icon: 'carbon',
        rpc: ['https://evm-api.carbon.network/'],
        faucets: [],
        nativeCurrency: {
            name: 'swth',
            symbol: 'SWTH',
            decimals: 18,
        },
        infoURL: 'https://carbon.network/',
        shortName: 'carbon',
        chainId: 9790,
        networkId: 9790,
        explorers: [],
    },
    {
        name: 'Smart Bitcoin Cash',
        chain: 'smartBCH',
        rpc: [
            'https://smartbch.greyh.at',
            'https://rpc-mainnet.smartbch.org',
            'https://smartbch.fountainhead.cash/mainnet',
            'https://smartbch.devops.cash/mainnet',
        ],
        faucets: [],
        nativeCurrency: {
            name: 'Bitcoin Cash',
            symbol: 'BCH',
            decimals: 18,
        },
        infoURL: 'https://smartbch.org/',
        shortName: 'smartbch',
        chainId: 10000,
        networkId: 10000,
    },
    {
        name: 'LoopNetwork Mainnet',
        chain: 'LoopNetwork',
        rpc: ['https://api.mainnetloop.com'],
        faucets: [],
        nativeCurrency: {
            name: 'LOOP',
            symbol: 'LOOP',
            decimals: 18,
        },
        infoURL: 'http://theloopnetwork.org/',
        shortName: 'loop',
        chainId: 15551,
        networkId: 15551,
        explorers: [
            {
                name: 'loopscan',
                url: 'http://explorer.mainnetloop.com',
                standard: 'none',
            },
        ],
    },
    {
        name: 'EOS EVM Network',
        chain: 'EOS',
        icon: 'eos',
        rpc: ['https://api.evm.eosnetwork.com'],
        faucets: [],
        nativeCurrency: {
            name: 'EOS',
            symbol: 'EOS',
            decimals: 18,
        },
        infoURL: 'https://eosnetwork.com/eos-evm',
        shortName: 'eos',
        chainId: 17777,
        networkId: 17777,
        explorers: [
            {
                name: 'EOS EVM Explorer',
                url: 'https://explorer.evm.eosnetwork.com',
                standard: 'EIP3091',
            },
        ],
        parent: {
            type: 'L2',
            chain: 'eip155-1',
            bridges: [
                {
                    url: 'https://bridge.evm.eosnetwork.com',
                },
                {
                    url: 'https://app.multichain.org',
                },
            ],
        },
    },
    {
        name: 'Bitgert Mainnet',
        chain: 'Brise',
        rpc: ['https://rpc.icecreamswap.com', 'https://mainnet-rpc.brisescan.com', 'https://chainrpc.com', 'https://serverrpc.com'],
        faucets: [],
        nativeCurrency: {
            name: 'Bitrise Token',
            symbol: 'Brise',
            decimals: 18,
        },
        infoURL: 'https://bitgert.com/',
        shortName: 'Brise',
        chainId: 32520,
        networkId: 32520,
        icon: 'brise',
        explorers: [
            {
                name: 'Brise Scan',
                url: 'https://brisescan.com',
                icon: 'brise',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Fusion Mainnet',
        chain: 'FSN',
        icon: 'fusion',
        rpc: ['https://mainnet.fusionnetwork.io', 'wss://mainnet.fusionnetwork.io'],
        features: [
            {
                name: 'EIP155',
            },
            {
                name: 'EIP1559',
            },
        ],
        faucets: [],
        nativeCurrency: {
            name: 'Fusion',
            symbol: 'FSN',
            decimals: 18,
        },
        infoURL: 'https://fusion.org',
        shortName: 'fsn',
        chainId: 32659,
        networkId: 32659,
        slip44: 288,
        explorers: [
            {
                name: 'fsnscan',
                url: 'https://fsnscan.com',
                icon: 'fsnscan',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Zilliqa EVM',
        chain: 'ZIL',
        rpc: ['https://api.zilliqa.com'],
        faucets: [],
        nativeCurrency: {
            name: 'Zilliqa',
            symbol: 'ZIL',
            decimals: 18,
        },
        infoURL: 'https://www.zilliqa.com/',
        shortName: 'zil',
        chainId: 32769,
        networkId: 32769,
        icon: 'zilliqa',
        explorers: [
            {
                name: 'Zilliqa EVM Explorer',
                url: 'https://evmx.zilliqa.com',
                standard: 'none',
            },
        ],
    },
    {
        name: 'OHO Mainnet',
        chain: 'OHO',
        rpc: ['https://mainnet.oho.ai'],
        faucets: [],
        nativeCurrency: {
            name: 'OHO',
            symbol: 'OHO',
            decimals: 18,
        },
        infoURL: 'https://oho.ai',
        shortName: 'oho',
        chainId: 39815,
        networkId: 39815,
        icon: 'oho',
        explorers: [
            {
                name: 'ohoscan',
                url: 'https://ohoscan.com',
                icon: 'ohoscan',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Arbitrum One',
        chainId: 42161,
        shortName: 'arb1',
        chain: 'ETH',
        networkId: 42161,
        nativeCurrency: {
            name: 'Ether',
            symbol: 'ETH',
            decimals: 18,
        },
        rpc: ['https://arb1.arbitrum.io/rpc'],
        faucets: [],
        explorers: [
            {
                name: 'Arbiscan',
                url: 'https://arbiscan.io',
                standard: 'EIP3091',
            },
            {
                name: 'Arbitrum Explorer',
                url: 'https://explorer.arbitrum.io',
                standard: 'EIP3091',
            },
        ],
        infoURL: 'https://arbitrum.io',
        parent: {
            type: 'L2',
            chain: 'eip155-1',
            bridges: [
                {
                    url: 'https://bridge.arbitrum.io',
                },
            ],
        },
    },
    {
        name: 'Arbitrum Nova',
        chainId: 42170,
        shortName: 'arb-nova',
        chain: 'ETH',
        networkId: 42170,
        nativeCurrency: {
            name: 'Ether',
            symbol: 'ETH',
            decimals: 18,
        },
        rpc: ['https://nova.arbitrum.io/rpc'],
        faucets: [],
        explorers: [
            {
                name: 'Arbitrum Nova Chain Explorer',
                url: 'https://nova-explorer.arbitrum.io',
                icon: 'blockscout',
                standard: 'EIP3091',
            },
        ],
        infoURL: 'https://arbitrum.io',
        parent: {
            type: 'L2',
            chain: 'eip155-1',
            bridges: [
                {
                    url: 'https://bridge.arbitrum.io',
                },
            ],
        },
    },
    {
        name: 'Celo Mainnet',
        chainId: 42220,
        shortName: 'celo',
        chain: 'CELO',
        networkId: 42220,
        nativeCurrency: {
            name: 'CELO',
            symbol: 'CELO',
            decimals: 18,
        },
        rpc: ['https://forno.celo.org', 'wss://forno.celo.org/ws'],
        faucets: ['https://free-online-app.com/faucet-for-eth-evm-chains/'],
        infoURL: 'https://docs.celo.org/',
        explorers: [
            {
                name: 'Celoscan',
                url: 'https://celoscan.io',
                standard: 'EIP3091',
            },
            {
                name: 'blockscout',
                url: 'https://explorer.celo.org',
                standard: 'none',
            },
        ],
    },
    {
        name: 'Oasis Emerald',
        chain: 'Emerald',
        icon: 'oasis',
        rpc: ['https://emerald.oasis.dev', 'wss://emerald.oasis.dev/ws'],
        faucets: [],
        nativeCurrency: {
            name: 'Emerald Rose',
            symbol: 'ROSE',
            decimals: 18,
        },
        infoURL: 'https://docs.oasis.io/dapp/emerald',
        shortName: 'emerald',
        chainId: 42262,
        networkId: 42262,
        explorers: [
            {
                name: 'Oasis Emerald Explorer',
                url: 'https://explorer.emerald.oasis.dev',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Avalanche C-Chain',
        chain: 'AVAX',
        icon: 'avax',
        rpc: ['https://api.avax.network/ext/bc/C/rpc', 'https://avalanche-c-chain.publicnode.com'],
        features: [
            {
                name: 'EIP1559',
            },
        ],
        faucets: ['https://free-online-app.com/faucet-for-eth-evm-chains/'],
        nativeCurrency: {
            name: 'Avalanche',
            symbol: 'AVAX',
            decimals: 18,
        },
        infoURL: 'https://www.avax.network/',
        shortName: 'avax',
        chainId: 43114,
        networkId: 43114,
        slip44: 9005,
        explorers: [
            {
                name: 'snowtrace',
                url: 'https://snowtrace.io',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'REI Network',
        chain: 'REI',
        rpc: ['https://rpc.rei.network', 'wss://rpc.rei.network'],
        faucets: [],
        nativeCurrency: {
            name: 'REI',
            symbol: 'REI',
            decimals: 18,
        },
        infoURL: 'https://rei.network/',
        shortName: 'REI',
        chainId: 47805,
        networkId: 47805,
        explorers: [
            {
                name: 'rei-scan',
                url: 'https://scan.rei.network',
                standard: 'none',
            },
        ],
    },
    {
        name: 'REI Chain Mainnet',
        chain: 'REI',
        icon: 'reichain',
        rpc: ['https://rei-rpc.moonrhythm.io'],
        faucets: ['http://kururu.finance/faucet?chainId=55555'],
        nativeCurrency: {
            name: 'Rei',
            symbol: 'REI',
            decimals: 18,
        },
        infoURL: 'https://reichain.io',
        shortName: 'reichain',
        chainId: 55555,
        networkId: 55555,
        explorers: [
            {
                name: 'reiscan',
                url: 'https://reiscan.com',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Godwoken Mainnet',
        chain: 'GWT',
        rpc: ['https://v1.mainnet.godwoken.io/rpc'],
        faucets: [],
        nativeCurrency: {
            name: 'pCKB',
            symbol: 'pCKB',
            decimals: 18,
        },
        infoURL: 'https://www.nervos.org',
        shortName: 'gw-mainnet-v1',
        chainId: 71402,
        networkId: 71402,
        explorers: [
            {
                name: 'GWScan Block Explorer',
                url: 'https://v1.gwscan.com',
                standard: 'none',
            },
        ],
    },
    {
        name: 'Polis Mainnet',
        chain: 'Olympus',
        icon: 'polis',
        rpc: ['https://rpc.polis.tech'],
        faucets: ['https://faucet.polis.tech'],
        nativeCurrency: {
            name: 'Polis',
            symbol: 'POLIS',
            decimals: 18,
        },
        infoURL: 'https://polis.tech',
        shortName: 'olympus',
        chainId: 333999,
        networkId: 333999,
    },
    {
        name: 'Kekchain',
        chain: 'kek',
        rpc: ['https://mainnet.kekchain.com'],
        faucets: [],
        nativeCurrency: {
            name: 'KEK',
            symbol: 'KEK',
            decimals: 18,
        },
        infoURL: 'https://kekchain.com',
        shortName: 'KEK',
        chainId: 420420,
        networkId: 103090,
        icon: 'kek',
        explorers: [
            {
                name: 'blockscout',
                url: 'https://mainnet-explorer.kekchain.com',
                icon: 'kek',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Vision - Mainnet',
        chain: 'Vision',
        rpc: ['https://infragrid.v.network/ethereum/compatible'],
        faucets: [],
        nativeCurrency: {
            name: 'VS',
            symbol: 'VS',
            decimals: 18,
        },
        infoURL: 'https://www.v.network',
        explorers: [
            {
                name: 'Visionscan',
                url: 'https://www.visionscan.org',
                standard: 'EIP3091',
            },
        ],
        shortName: 'vision',
        chainId: 888888,
        networkId: 888888,
        slip44: 60,
    },
    {
        name: 'Aurora Mainnet',
        chain: 'NEAR',
        rpc: ['https://mainnet.aurora.dev'],
        faucets: [],
        nativeCurrency: {
            name: 'Ether',
            symbol: 'ETH',
            decimals: 18,
        },
        infoURL: 'https://aurora.dev',
        shortName: 'aurora',
        chainId: 1313161554,
        networkId: 1313161554,
        explorers: [
            {
                name: 'aurorascan.dev',
                url: 'https://aurorascan.dev',
                standard: 'EIP3091',
            },
        ],
    },
    {
        name: 'Harmony Mainnet Shard 0',
        chain: 'Harmony',
        rpc: ['https://api.harmony.one', 'https://api.s0.t.hmny.io'],
        faucets: ['https://free-online-app.com/faucet-for-eth-evm-chains/'],
        nativeCurrency: {
            name: 'ONE',
            symbol: 'ONE',
            decimals: 18,
        },
        infoURL: 'https://www.harmony.one/',
        shortName: 'hmy-s0',
        chainId: 1666600000,
        networkId: 1666600000,
        explorers: [
            {
                name: 'Harmony Block Explorer',
                url: 'https://explorer.harmony.one',
                standard: 'EIP3091',
            },
        ],
    },
];
