#!/usr/bin/env sh
echo "HUSKY commit-msg"

. "$(dirname -- "$0")/_/husky.sh"

if ! head -1 "$1" | grep -qE "^.{1,100}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi

npx commitlint --edit "${1}"
